# Generated by Django 5.0.6 on 2024-06-14 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Type Category',
                'verbose_name_plural': 'Type Categories',
                'db_table': 'type_category',
            },
        ),
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mount')),
                ('note', models.TextField(blank=True, null=True)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses1.categorymodel')),
            ],
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='fk_id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses1.typecategorymodel'),
        ),
    ]
